### ISSUE TITLE
USB to Serial Driver 0665:5161 Trouble

### ISSUE THREAD

**Issue by Klauzen** [opengd/solar-sis#15]
Hi, thank for publishing this project!
I have some trouble using solar-sis with my PIP3024MXE via Raspberry Zero W.
I can't find a ttyUSB0 (or other port), to get a connection to the USB/Serial Converter (by using the PIP4085 example).

`pi@raspberrypi:~ $ ls /dev/tty*
/dev/tty    /dev/tty19  /dev/tty3   /dev/tty40  /dev/tty51  /dev/tty62
/dev/tty0   /dev/tty2   /dev/tty30  /dev/tty41  /dev/tty52  /dev/tty63
/dev/tty1   /dev/tty20  /dev/tty31  /dev/tty42  /dev/tty53  /dev/tty7
/dev/tty10  /dev/tty21  /dev/tty32  /dev/tty43  /dev/tty54  /dev/tty8
/dev/tty11  /dev/tty22  /dev/tty33  /dev/tty44  /dev/tty55  /dev/tty9
/dev/tty12  /dev/tty23  /dev/tty34  /dev/tty45  /dev/tty56  /dev/ttyAMA0
/dev/tty13  /dev/tty24  /dev/tty35  /dev/tty46  /dev/tty57  /dev/ttyprintk
/dev/tty14  /dev/tty25  /dev/tty36  /dev/tty47  /dev/tty58
/dev/tty15  /dev/tty26  /dev/tty37  /dev/tty48  /dev/tty59
/dev/tty16  /dev/tty27  /dev/tty38  /dev/tty49  /dev/tty6
/dev/tty17  /dev/tty28  /dev/tty39  /dev/tty5   /dev/tty60
/dev/tty18  /dev/tty29  /dev/tty4   /dev/tty50  /dev/tty61
`
I can read the driver's ID via lsusb: 0665:5161 Cypress Semiconductor USB to Serial
And I allready read, that there are some troubles, to get up running this USB to Serial adapter.

I guess, the problem could be, that I can't install the old version of serialport (4.0.7). I just can install newer ones (8.0.7)
`pi@raspberrypi:~ $ npm -v
6.13.7
pi@raspberrypi:~ $ node -v
v11.15.0
`
What else could I try? Use a Raspberry Pi 4? Thanks!

**Comment by cybertza** [comment]
Hi

I eventually used device-by-id rather for the connection, and that seems to have worked the best.

you can test in a few ways, if you do: `# screen /<device-by-id> 2400`
and type anything, it should reply with a NAKK then you know you have comms working via serial
EG: `"serial_port": "/dev/serial/by-id/usb-FTDI_USB-RS232_Cable_FT1Y00GS-if00-port0"
`
so #ls /dev/serial/by-id
i then did a chmod 777 for it, coz im lazy and do know any better.
and then the software was working great for me, since i had more than one serial this was a surefire way. 

~$ node -v
v8.10.0
npm -v
3.5.2


first confirm your serial is working with screen, and then you can see if its a node issue, the node serial i found is just an issue with hidraw@2400.

Let me know
